# Setup
title:        Truth's Blog
tagline:      代码，是写给人看的
baseurl:      "https://truth-nju.github.io/"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Truth
  url:        https://truth-nju.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
