# Setup
title:        Truth's Blog
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Truth
  url:        https://truth-nju.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
